version: '2'
services:
  # web UI combining all services into single interface
  muximux:
    hostname: muximux
    container_name: muximux
    image: linuxserver/muximux
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8081:80
    volumes:
      - ${base}/muximux/config:/config

  # bittorrent client/indexer running through anonymous VPN
  # app container ports exposed via VPN container
  # hydra=5075 radarr=7878 deluge=8112 sonarr=8989
  media-vpn:
    hostname: media-vpn
    container_name: media-vpn
    image: openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 5075:5075
      - 7878:7878
      - 8112:8112
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - FORCEVPN=true
    volumes:
      - ${base}/media-vpn/config:/config

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: always
    network_mode: service:media-vpn
    depends_on:
      - media-vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${base}/deluge/config:/config
      - ${dl}:/downloads

  # usenet client/indexer
  nzbget:
    hostname: nzbget
    container_name: nzbget
    image: linuxserver/nzbget
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 6789:6789
    volumes:
      - ${base}/nzbget/config:/config
      - ${dl}:/downloads
      - ${media}:/media

  hydra:
    container_name: hydra
    image: linuxserver/hydra
    restart: always
    depends_on:
      - media-vpn
      - nzbget
    network_mode: service:media-vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${base}/hydra/config:/config

  # media watchers/grabbers
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: always
    depends_on:
      - media-vpn
      - nzbget
      - hydra
      - deluge
    network_mode: service:media-vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${base}/radarr/config:/config
      - ${dl}:/downloads
      - ${media}/video/Movies:/movies

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: always
    depends_on:
      - media-vpn
      - nzbget
      - hydra
      - deluge
    network_mode: service:media-vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${base}/sonarr/config:/config
      - ${dl}:/downloads
      - ${media}/video/TV\ Shows:/tv

networks:
  default:
